version: "3.8"

services:
  php:
    image: wordpress:php8.1-fpm
    container_name: wp-php
    restart: unless-stopped
    env_file:
      - .env
    environment:
      WP_DB_HOST: mysql:3306
      WP_DB_USER: ${MYSQL_USER}
      WP_DB_PASSWORD: ${MYSQL_PASSWORD}
      WP_DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - wp-network
    mem_limit: 768m
    security_opt:
      - no-new-privileges:true

  nginx:
    image: nginx:1.25-alpine
    container_name: wp-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./wordpress:/var/www/html:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - php
    networks:
      - wp-network
    mem_limit: 128m
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run

  mysql:
    image: mysql:5.7
    container_name: wp-mysql
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - wp-network
    mem_limit: 768m
    security_opt:
      - no-new-privileges:true

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wp-phpmyadmin
    restart: unless-stopped
    ports:
      - "127.0.0.1:8081:80"   # ðŸ‘ˆ solo acceso local
    env_file:
      - .env
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - wp-network
    mem_limit: 256m
    security_opt:
      - no-new-privileges:true

  wp-cli:
    image: wordpress:cli
    container_name: wp-cli
    depends_on:
      - php
      - mysql
    volumes:
      - ./wordpress:/var/www/html
    user: "33:33"
    env_file:
      - .env
    environment:
      WP_DB_HOST: mysql:3306
      WP_DB_USER: ${MYSQL_USER}
      WP_DB_PASSWORD: ${MYSQL_PASSWORD}
      WP_DB_NAME: ${MYSQL_DATABASE}
    networks:
      - wp-network
    profiles:
      - tools   # ðŸ‘ˆ no se levanta por defecto

  certbot:
    image: certbot/certbot
    container_name: wp-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - wp-network
    profiles:
      - tools

  certbot-renew:
    image: certbot/certbot
    container_name: wp-certbot-renew
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - wp-network
    entrypoint: >
      /bin/sh -c
      "trap exit TERM;
       while :; do
         certbot renew;
         sleep 12h & wait $${!};
       done"

networks:
  wp-network:
    driver: bridge
